name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: CI
      uses: actions/setup-node@v4
      with:
          node-version: '20.x'
    - run: npm install
    - name: Pass github
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Automate changes to files"
        git push
    - run: npm run deploy
