name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: CI
      uses: actions/setup-node@v4
      with:
          node-version: '20.x'
    - run: npm install

    - name: CD
      uses: actions/setup-node@v4
      with:
          node-version: '20.x'
    - run: npm run deploy
